Source/Jobs/Areas/Rug/Controllers/ProcessSequenceLineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model.Models;
using Data.Models;
using Service;
using Data.Infrastructure;
using Core.Common;
using Model.ViewModels;
using AutoMapper;
using Jobs.Constants.DocumentType;
using Model.ViewModel;
using System.Xml.Linq;
using Jobs.Helpers;

namespace Jobs.Areas.Rug.Controllers
{

    [Authorize]
    public class ProcessSequenceLineController : System.Web.Mvc.Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        ActiivtyLogViewModel LogVm = new ActiivtyLogViewModel();

        IProcessSequenceLineService _ProcessSequenceLineService;
        IUnitOfWork _unitOfWork;
        IExceptionHandlingService _exception;

        public ProcessSequenceLineController(IProcessSequenceLineService ProcessSequence, IUnitOfWork unitOfWork, IExceptionHandlingService exec)
        {
            _ProcessSequenceLineService = ProcessSequence;
            _unitOfWork = unitOfWork;
            _exception = exec;

            //Log Initialization
            LogVm.SessionId = 0;
            LogVm.ControllerName = System.Web.HttpContext.Current.Request.RequestContext.RouteData.GetRequiredString("controller");
            LogVm.ActionName = System.Web.HttpContext.Current.Request.RequestContext.RouteData.GetRequiredString("action");
            LogVm.User = System.Web.HttpContext.Current.Request.RequestContext.HttpContext.User.Identity.Name;
        }

        [HttpGet]
        public JsonResult Index(int id)
        {
            var p = _ProcessSequenceLineService.GetProcessSequenceLineListForProductCollectionIndex(id);
            return Json(p, JsonRequestBehavior.AllowGet);

        }

        private void PrepareViewBag(ProcessSequenceLineViewModel s)
        {
            if (s == null)
            {
                ViewBag.ProcessId = new SelectList(new ProcessService(_unitOfWork).GetProcessList(), "ProcessId", "ProcessName");
            }
            else
            {
                ViewBag.ProcessId = new SelectList(new ProcessService(_unitOfWork).GetProcessList(), "ProcessId", "ProcessName", s.ProcessId);
            }
        }

        public ActionResult _CreateForProductCollection(int Id) //Id ==>ProductCalculationId
        {
            ProcessSequenceHeader H = new ProcessSequenceHeaderService(_unitOfWork).GetProcessSequenceHeaderForProductCollection(Id);
            ProcessSequenceLineViewModel s = new ProcessSequenceLineViewModel();
            s.RefDocId = Id;
            s.RefDocTypeId = H.ReferenceDocTypeId;
            s.ProcessSequenceHeaderId = H.ProcessSequenceHeaderId;
            PrepareViewBag(null);
            return PartialView("_Create", s);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _CreatePost(ProcessSequenceLineViewModel svm)
        {
            ProcessSequenceLine s = Mapper.Map<ProcessSequenceLineViewModel, ProcessSequenceLine>(svm);
            ProcessSequenceHeader temp = (from p in db.ProcessSequenceHeader
                                          where p.ProcessSequenceHeaderId == svm.ProcessSequenceHeaderId
                                          select p).FirstOrDefault();

            ProductCategory PColl = new ProductCategoryService(_unitOfWork).Find(svm.RefDocId.Value);


            if (ModelState.IsValid)
            {
                if (svm.ProcessSequenceLineId <= 0)
                {

                    if (temp == null)
                    {
                        int RefDocTypeId = new DocumentTypeService(_unitOfWork).Find(DocumentTypeConstants.ProductCategory.DocumentTypeName).DocumentTypeId;

                        ProcessSequenceHeader Header = new ProcessSequenceHeader();
                        Header.ProcessSequenceHeaderName = PColl.ProductCategoryName + "-" + new DivisionService(_unitOfWork).Find((int)HttpContext.Session["DivisionId"]).DivisionName;
                        Header.ReferenceDocTypeId = RefDocTypeId;
                        Header.ReferenceDocId = PColl.ProductCategoryId;
                        Header.CreatedBy = User.Identity.Name;
                        Header.CreatedDate = DateTime.Now;
                        Header.ModifiedBy = User.Identity.Name;
                        Header.ModifiedDate = DateTime.Now;
                        Header.ObjectState = Model.ObjectState.Added;

                        new ProcessSequenceHeaderService(_unitOfWork).Create(Header);

                        s.ProcessSequenceHeaderId = Header.ProcessSequenceHeaderId;
                    }
                    else
                    {
                        s.ProcessSequenceHeaderId = temp.ProcessSequenceHeaderId;
                    }

                    s.CreatedDate = DateTime.Now;
                    s.ModifiedDate = DateTime.Now;
                    s.CreatedBy = User.Identity.Name;
                    s.ModifiedBy = User.Identity.Name;
                    s.ObjectState = Model.ObjectState.Added;
                    _ProcessSequenceLineService.Create(s);

                    if (temp != null && temp.Status != (int)StatusConstants.Drafted)
                    {
                        temp.Status = (int)StatusConstants.Modified;
                        new ProcessSequenceHeaderService(_unitOfWork).Update(temp);
                    }

                    try
                    {
                        _unitOfWork.Save();
                    }

                    catch (Exception ex)
                    {
                        string message = _exception.HandleException(ex);
                        ModelState.AddModelError("", message);
                        return PartialView("_Create", svm);
                    }

                    LogActivity.LogActivityDetail(LogVm.Map(new ActiivtyLogViewModel
                    {
                        DocTypeId = new DocumentTypeService(_unitOfWork).FindByName(DocumentTypeConstants.ProcessSequence.DocumentTypeName).DocumentTypeId,
                        DocId = s.ProcessSequenceHeaderId,
                        DocLineId = s.ProcessSequenceLineId,
                        ActivityType = (int)ActivityTypeContants.Added,
                    }));

                    return RedirectToAction("_CreateForProductCollection", new { id = svm.RefDocId });
                }
                else
                {
                    List<LogTypeViewModel> LogList = new List<LogTypeViewModel>();

                    ProcessSequenceHeader header = new ProcessSequenceHeaderService(_unitOfWork).Find(svm.ProcessSequenceHeaderId);
                    int status = header.Status;
                    ProcessSequenceLine temp1 = _ProcessSequenceLineService.Find(svm.ProcessSequenceLineId);

                    ProcessSequenceLine ExRec = Mapper.Map<ProcessSequenceLine>(temp1);

                    temp1.ProcessId = svm.ProcessId;
                    temp1.Sequence = svm.Sequence;
                    temp1.ProductRateGroupId = svm.ProductRateGroupId;
                    temp1.Days = svm.Days;
                    temp1.ModifiedDate = DateTime.Now;
                    temp1.ModifiedBy = User.Identity.Name;
                    _ProcessSequenceLineService.Update(temp1);


                    LogList.Add(new LogTypeViewModel
                    {
                        ExObj = ExRec,
                        Obj = temp1,
                    });
                    XElement Modifications = new ModificationsCheckService().CheckChanges(LogList);

                    try
                    {
                        _unitOfWork.Save();
                    }

                    catch (Exception ex)
                    {
                        string message = _exception.HandleException(ex);
                        ModelState.AddModelError("", message);
                        return PartialView("_Create", svm);
                    }

                    LogActivity.LogActivityDetail(LogVm.Map(new ActiivtyLogViewModel
                    {
                        DocTypeId = new DocumentTypeService(_unitOfWork).FindByName(DocumentTypeConstants.ProcessSequence.DocumentTypeName).DocumentTypeId,
                        DocId = temp.ProcessSequenceHeaderId,
                        DocLineId = temp1.ProcessSequenceLineId,
                        ActivityType = (int)ActivityTypeContants.Modified,
                        xEModifications = Modifications,
                    }));

                    return Json(new { success = true });

                }
            }
            PrepareViewBag(svm);
            return PartialView("_Create", svm);
        }

        [HttpGet]
        public ActionResult _Edit(int id)
        {
            ProcessSequenceLine temp = _ProcessSequenceLineService.GetProcessSequenceLine(id);

            ProcessSequenceHeader H = new ProcessSequenceHeaderService(_unitOfWork).GetProcessSequenceHeader(temp.ProcessSequenceHeaderId);
            ViewBag.DocNo = H.ProcessSequenceHeaderName;
            ProcessSequenceLineViewModel s = Mapper.Map<ProcessSequenceLine, ProcessSequenceLineViewModel>(temp);

            s.RefDocId = H.ReferenceDocId;
            s.RefDocTypeId = H.ReferenceDocTypeId;

            PrepareViewBag(s);

            if (temp == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Create", s);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProcessSequenceLineViewModel ProcessSequenceLine = _ProcessSequenceLineService.GetProcessSequenceLineModel(id);
            if (ProcessSequenceLine == null)
            {
                return HttpNotFound();
            }
            return View(ProcessSequenceLine);
        }


        [HttpPost, ActionName("Delete")]

Source/Jobs/Areas/Rug/Views/ProcessSequenceLine/_Create.cshtml
@model Model.ViewModels.ProcessSequenceLineViewModel
@using Core.Common

<div class="modal-content">
    <div class="modal-header" style="border-bottom: 1px solid #8E8888">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"> <span class="glyphicon glyphicon-remove"></span></button>
        <h3>
            <span style="font-family: Calibri,sans-serif,Verdana;font-weight:bold" class="black"><span class="glyphicon glyphicon-file black"></span> Process Detail</span>
        </h3>
    </div>
    <div>
        @using (Html.BeginForm("_CreatePost", "ProcessSequenceLine", FormMethod.Post, new { enctype = "multipart/form-data", id = "modform" }))
        {
            @Html.AntiForgeryToken()

            @Html.HiddenFor(model => model.ProcessSequenceHeaderId)
            @Html.HiddenFor(m => m.ProcessSequenceLineId)
            @Html.HiddenFor(m => m.RefDocTypeId)
            @Html.HiddenFor(m => m.RefDocId)

            <div class="form-horizontal modal-body">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row">

                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.ProcessId, "Process", new { @class = "control-label col-md-4 col-sm-2" })
                            <div class="col-md-7 col-sm-10">
                                @Html.TextBoxFor(model => model.ProcessId, new { @class = "form-control col-xs-7 required" })
                                @Html.ValidationMessageFor(model => model.ProcessId, "", new { @class = "text-danger" })
                                <span id="status" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Sequence, "Serial", new { @class = "control-label col-md-4 col-sm-2 " })
                            <div class="col-md-7 col-sm-10">
                                @Html.TextBoxFor(model => model.Sequence, new { @class = "form-control col-xs-7 required" })
                                @Html.ValidationMessageFor(model => model.Sequence, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Days, "Days", new { @class = "control-label col-md-4 col-sm-2" })
                            <div class="col-md-7 col-sm-10">
                                @Html.TextBoxFor(model => model.Days, new { @class = "form-control col-xs-7 required" })
                                @Html.ValidationMessageFor(model => model.Days, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.ProductRateGroupId, "Product RateGroup", new { @class = "control-label col-md-4 col-sm-2" })
                            <div class="col-md-7 col-sm-10">
                                @Html.TextBoxFor(model => model.ProductRateGroupId, new { @class = "form-control col-xs-7 required" })
                                @Html.ValidationMessageFor(model => model.ProductRateGroupId, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>


                <div class="modal-footer " style="padding: 19px 20px 0 20px; border-top:1px solid #8E8888">
                    <button class="btn custom left" name="Command:Edit" type="submit"><h2 style="margin:0px" id="submit"><span class="glyphicon glyphicon-floppy-disk black"></span> </h2></button>
                    <button class="btn custom" name="Command:Delete" id="delete" type="submit"><h2 style="margin:0px"><span class="glyphicon glyphicon-trash black"></span> </h2></button>
                </div>
            </div>
        }
    </div>
</div>


<script type="text/javascript">
    $(document).ready(function () {
        CustomSelectFunction($("#ProcessId"), '/ComboHelpList/GetProcess', '/ComboHelpList/SetSingleProcess', 'Enter Process Name', false, 0);
        CustomSelectFunction($("#ProductRateGroupId"), '/ComboHelpList/GetProductRateGroup', '/ComboHelpList/SetProductRateGroup', 'Enter Product Name', false, 1,0);

        $("#ProcessId").select2("focus");


        var id=@Model.ProcessSequenceLineId;
        $('#delete','.modal-content').click(function (e) {
            if(id>0)
            {
                var url = '/ProcessSequenceLine/DeletePost';
                $('form#modform').attr('action',url);
                return;
            }
            else
            {
                return false;
            }
        });

        var IsSaved=false;
        var ValidationCount=0;

        $('#modform').bind('submit',function(event){

            if(!IsSaved)
            {
                if(!ValidateData())
                {
                    return false;
                }
                IsSaved=true;
                $('button:submit').attr('disabled','disabled');
                return IsSaved;
            }
            else
            {
                return false;
            }


        });

        function ValidateData() {
            var ValidationMessage = "";

            //Client Side Validaion.....

            return  (ValidationMessage=="");

        }

    });

</script>

Source/Jobs/Areas/Rug/Views/ProcessSequenceLine/_Edit.cshtml
@model Surya.India.Model.ViewModels.SaleOrderLineViewModel
@using Surya.India.Core.Common


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add new Product</h4>
    </div>


    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.SaleOrderHeaderId)
    @Html.HiddenFor(m=>m.SaleOrderLineId)
    @Html.HiddenFor(m => m.UnitId)
    @Html.HiddenFor(m => m.UnitConversionMultiplier)

    <div class="modal-body">

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row">

                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.ProductId, "Product", htmlAttributes: new { @class = "control-label col-xs-4 " })
                        <div class="col-xs-6">
                            @Html.TextBoxFor(model => model.ProductId, new { @class = "form-control col-xs-5 required" })
                            @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Specification, "Specification", htmlAttributes: new { @class = "control-label col-xs-4 " })
                        <div class="col-xs-6">
                            @Html.TextBoxFor(model => model.Specification, new { @class = "form-control col-xs-5 required" })
                            @Html.ValidationMessageFor(model => model.Specification, "", new { @class = "text-danger" })
                        </div>
                    </div>

                </div>

            </div>

            <div class="row">

                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Qty, htmlAttributes: new { @class = "control-label col-xs-4" })
                        <div class="col-xs-6">
                            @Html.TextBoxFor(model => model.Qty, new { @class = "form-control col-xs-5 required" })
                            @Html.ValidationMessageFor(model => model.Qty, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.DueDate, htmlAttributes: new { @class = "control-label col-xs-4" })
                        <div class="col-xs-6">
                            @Html.TextBoxFor(model => model.DueDate, "{0:dd/MMMM/yyyy}", new { @class = "datepicker form-control col-xs-5 required" })
                            @Html.ValidationMessageFor(model => model.DueDate, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">

                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.DeliveryUnitId, htmlAttributes: new { @class = "control-label col-xs-4" })
                        <div class="col-xs-6">
                            @Html.DropDownListFor(model => model.DeliveryUnitId, new SelectList(ViewBag.DeliveryUnitList as System.Collections.IEnumerable, "UnitId", "UnitName"), new { @class = "form-control col-xs-5 required" })
                            @Html.ValidationMessageFor(model => model.DeliveryUnitId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.DeliveryQty, "Delivery Qty*", htmlAttributes: new { @class = "control-label col-xs-4" })
                        <div class="col-xs-6">
                            @Html.TextBoxFor(model => model.DeliveryQty, new { @class = "form-control col-xs-5 required" })
                            @Html.ValidationMessageFor(model => model.DeliveryQty, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">

                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Rate, htmlAttributes: new { @class = "control-label col-xs-4" })
                        <div class="col-xs-6">
                            @Html.TextBoxFor(model => model.Rate, new { @class = "form-control col-xs-5 required" })
                            @Html.ValidationMessageFor(model => model.Rate, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Amount, "Amount", htmlAttributes: new { @class = "control-label col-xs-4" })
                        <div class="col-xs-6">
                            @Html.TextBoxFor(model => model.Amount, new { @class = "form-control col-xs-5 required" })
                            @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">

                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.SalesTaxGroupId, htmlAttributes: new { @class = "control-label col-xs-4" })
                        <div class="col-xs-6">
                            @Html.TextBoxFor(model => model.SalesTaxGroupId, new { @class = "form-control col-xs-5 required", @readonly = true })
                            @Html.ValidationMessageFor(model => model.SalesTaxGroupId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Remark, htmlAttributes: new { @class = "control-label col-xs-4" })
                        <div class="col-xs-6">
                            @Html.TextBoxFor(model => model.Remark, new { @class = "form-control col-xs-5 required" })
                            @Html.ValidationMessageFor(model => model.Remark, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="modal-footer">
        <input class="btn btn-primary" type="submit" value="Save" />
        <button class="btn" data-dismiss="modal">Cancel</button>

    </div>
}
<script>
    $(document).ready(function () {

        CustomSelectFunction($("#ProductId"), '/ComboHelpList/GetProducts', '/ComboHelpList/SetSingleProducts', 'Enter Product Name', false, 3);



    });

</script>

<script type="text/javascript">
    $(function () {
        GetProductDetail.call();
        $("#DeliveryQty,#Rate,#Amount,#Qty").keyup(Calculation);
        $("#DeliveryUnitId").change(GetUnitConversionMultiplier);
        $("#ProductId").change(GetProductDetail);
        $("#ProductId").change(CheckForValidation);



        function GetProductDetail() {
            var ProcessProgress = $("#Product detail loading progress");
            ProcessProgress.show();
            if ($("#ProductId").val() != 0 || $("#ProductId").val() != NULL) {
                $.ajax({
                    cache: false,
                    type: "POST",
                    url: "@(Url.Action("GetProductDetailJson"))",
                    data: { ProductId: $("#ProductId").val() },
                    success: function (data) {
                        $("#Rate").val(data[0].StandardCost);
                        $("#UnitId").val(data[0].UnitId);
                        $("#DeliveryUnitId").val(data[0].UnitId);
                        GetUnitConversionMultiplier.call();
                        Calculation.call();
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert('Failed to retrieve product details.' + thrownError);
                        ProcessProgress.hide();
                    }
                });
            }

        }

        function CheckForValidation() {
            if ($("#ProductId").val() != 0||$("#ProductId").val() !=NULL)
            {
                $.ajax({
                    cache: false,
                    type: "POST",
                    url: "@(Url.Action("CheckForValidationinEdit"))",
                    data: { ProductId: $("#ProductId").val(), SaleOrderHeaderId: $("#SaleOrderHeaderId").val(), SaleOrderLineId: $("#SaleOrderLineId").val() },
                success: function (data) {
                    var status = data;
                    if (data.returnvalue)
                        $("#status").text("The Product Already exists in this order");
                    else
                        $("#status").text(" ");
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Failed to Check Validation.' + thrownError);
                }
            });
        }

    }

        function GetUnitConversionMultiplier() {

            if ($("#UnitId").val() == $("#DeliveryUnitId").val()) {
                $("#UnitConversionMultiplier").val(1);
                Calculation.call();
            }

            else {
                var ProcessProgress = $("#Unit conversion detail loading progress");
                ProcessProgress.show();
                $.ajax({
                    cache: false,
                    type: "POST",
                    url: "@(Url.Action("GetUnitConversionDetailJson"))",
                    data: { ProductId: $("#ProductId").val(), UnitId: $("#UnitId").val(), DeliveryUnitId: $("#DeliveryUnitId").val() },

                success: function (data) {
                    $("#UnitConversionMultiplier").val(data[0].Value);
                    Calculation.call();
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Failed to retrieve Unit conversion details.' + thrownError);
                    ProcessProgress.hide();
                }
            });
        }
    }


        function Calculation() {
            if ($('#UnitConversionMultiplier').val() != 0) {
                $('#DeliveryQty').val($('#Qty').val() * $('#UnitConversionMultiplier').val())
            }
            //$('#DeliveryQty').val($('#Qty').val())

            $('#Amount').val($('#DeliveryQty').val() * $('#Rate').val());
        }



    });
</script>

<script type="text/javascript">
    $(document).ready(function () {
        $("#ProductId").select2("focus");
    })

    $('.datepicker').datepicker({
        format: 'dd/MM/yyyy',
        "setDate": new Date(),
        "autoclose": true

    })
</script>